# Configuration file for EasyCAT based ForceSensor Slave
vendor_id: 0x0000079a
product_id: 0xdeadbeef
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x0006, sub_index: 1, type: int16, state_interface: force.0}
      - {index: 0x0006, sub_index: 2, type: int16, state_interface: force.1}
sm:  # Sync Manager
  - {index: 0, type: input, pdo: tpdo, watchdog: disable}
