vendor_id:  0x0000009a
product_id: 0x00030924
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: false  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
period: 125  # Hz
sdo:  # sdo data to be transferred at drive startup
  - {index: 0x1c32, sub_index: 1, type: int32, value: 2} 
  - {index: 0x1c33, sub_index: 1, type: int32, value: 2} 
  - {index: 0x60C2, sub_index: 1, type: int8, value: 8}
  - {index: 0x60C2, sub_index: 2, type: int8, value: -3}
  - {index: 0x6060, sub_index: 0, type: uint8, value: 8} 
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
    - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan}  # Target position
    - {index: 0x60fe, sub_index: 0, type: int32, command_interface： ~, efault: .nan}  # Physical outputs   
    - {index: 0x6040, sub_index: 0, type: uint16,command_interface: ~, default: 0}  # Control word
        
      
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a03
    channels:     
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position}  
      - {index: 0x60fd, sub_index: 0, type: int32, state_interface: ~}  
      - {index: 0x606c, sub_index: 0, type: int32, state_interface: velocity} 
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: ~}  # Status word

